[package]
name = "model-builder"
version = "0.1.0"
edition = "2018"

[dependencies]
phf_codegen = "0.10.0"
zip = "0.5.13"
serde_json = "1.0.78"
serde = { version = "1.0.136", features = ["derive"] }
common = { path = "../common" }
