[package]
name = "model-builder"
version = "0.1.0"
edition = "2018"

[dependencies]
rkyv = "0.7.36"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.79"
zip = "0.5.13"
common = { path = "../common" }
